SCM-NV/qmflows

- .gitignore
- src/qmflows/utils.py
- test/test_restart_init.py
Added the ``init_restart()`` function and ``InitRestart()`` context manager for calling the PLAMS [``init()``](https://www.scm.com/doc/plams/components/functions.html#scm.plams.core.functions.init) function without creating a new directory.
> Added init_restart() and InitRestart()

- .gitignore
- src/qmflows/packages/SCM.py
- src/qmflows/packages/cp2k_package.py
- src/qmflows/packages/gamess.py
- src/qmflows/packages/orca.py
- src/qmflows/packages/packages.py
Major
------
* Added the ``dill_path`` keyword to ``Package.__init__()`` and it's subclasses. It should take the path to a pickled ``plams.Results`` instance as value (_i.e._ the ``.dill`` file) and store it in the new ``Package.results`` property.
* The Results-containing .dill file, which is contained within the ``Pacakge.results`` property, is automatically unpacked whenever getting ``Package.results`` or getting a non-existing attribute. ``Pacakge.results`` is henceforth replaced with the ``plams.Results`` instance itself and all of its non-magic/non-private methods are added to the ``Pacakge`` as instance variables.
For example:
```
>>> from qmflows.packages.SCM import ADF_Result
>>> result = ADF_Result(...)
>>> print(result.results)
<scm.plams.interfaces.adfsuite.adf.ADFResults …
```
> Package & Result additions

- docs/conf.py
- requirements.txt
- setup.py
- src/qmflows/cp2k_utils.py
- test/test_cp2k_utils.py
* Marked QMFlows as a typed package (see [PEP 561](https://www.python.org/dev/peps/pep-0561/#id5)).
* Added the PLAMS repository on GitHub to the ``requirements.txt`` file. This should prevent readthedocs from using the outdated PyPi repository.
* Added the ``prm_to_df()`` function in ``qfmlows.cp2k_utils``: Traverse the passed CP2K settings and convert all forcefield parameter blocks into DataFrames.
> Added the prm_to_df() function

- src/qmflows/packages/cp2k_mm.py
- src/qmflows/packages/packages.py
- src/qmflows/packages/serializer.py
* Moved all ``Serializer`` subclasses to their own module.
* Added type-hints to the ``Serializer`` subclasses.
* Added a ``Serializer`` subclass for ``pandas.DataFrame`` and ``pandas.Series``.
* FIxed a bug where two positional arguments in ``CP2K_MM.run_job()`` were swapped around.
> Added Serializers for pandas

- src/qmflows/packages/SCM.py
Adds the ``ADF_Result.geometry`` and ``DFTB_Result.geometry`` properties, thus allowing one to extract optimized geometries via the same keyword as ``CP2K_Result`` (see below). https://github.com/SCM-NV/qmflows/blob/b979d92a1d46ff188d90d05e71e66f86649a0091/src/qmflows/data/dictionaries/propertiesCP2K.yaml#L12-L15
> Added the geometry property to `ADF_Result` and `DFTB_Result`

- src/qmflows/packages/SCM.py
- test/test_adf_mock.py
The ``ADF_Result`` currently takes an extra parameter (compared to all other ``Result`` classes) by the name of ``path_t21``. This extra argument is not accounted from whenever a job crashes, thus causing problems in the lines of code below (_i.e._ it raises a ``TypeError: __init__() missing 1 required positional argument: 'path_t21'``). https://github.com/SCM-NV/qmflows/blob/5e8a2259b3bbcf532099373768fe07537377a415/src/qmflows/packages/packages.py#L346-L369
The herein implemented solution does the following two things:
* Remove the ``path_t21`` parameter from ``ADF_Result.__init__()``.
* Internally construct the tape21 path using the ``plams_dir`` parameter, similar to how ``DFTB_Result.__init__()`` does it.
> Remove the `path_t21` parameter from `ADF_Result.__init__()`

- setup.py
- test/test_cp2k_mock.py
For some reason the GitHub actions tests are failing for Python 3.8 ([ref](https://github.com/SCM-NV/qmflows/runs/720617083?check_suite_focus=true)) after https://github.com/SCM-NV/qmflows/pull/194 and https://github.com/SCM-NV/qmflows/pull/195. Note that they're working fine on travis.
Based on the following piece of code it seems that the orbital eigenvalues (``orbs.eigenVals``) are either set to ``nan`` or contain a ``nan`` value somewhere. https://github.com/SCM-NV/qmflows/blob/4be2b847aeaf814bddcd61ad51f66e84ba618f7b/test/test_cp2k_mock.py#L58-L69
TODO
------
> Fix GitHub Actions test

- CHANGELOG.md
- src/qmflows/__init__.py
- src/qmflows/__version__.py
- src/qmflows/packages/packages.py
Implementation of https://github.com/SCM-NV/qmflows/issues/197:
* Exposed ``InitRestart`` to the main QMFlows ``__init__.py`` file.
* Exchanged ``plams.init()`` / ``plams.finish()`` for ``qmflows.InitRestart`` in the ``qmflows.run()`` function.
* Store the ``cache.db`` file in the PLAMS working directory.
> Use `InitRestart` when running QMFlows jobs

- CHANGELOG.md
- src/qmflows/__version__.py
- src/qmflows/packages/cp2k_package.py
* Allow other cp2k executable: ``cp2k.sopt``, ``cp2k.psmp``, etc.
> allow other cp2k executables

- .github/workflows/pythonapp.yml
* Replaced `conda --version` and `python --version` with the more informative `conda info` and `conda list` commands.
* Removed the `pip install pytest pytest-cov` statement. Both dependencies are already installed prior via `pip install -e .[test]`.
* Let `setup.cfg` handle which directories should be tested.
> Cleaned up the `build with conda` recipe a bit

- .github/workflows/pythonapp.yml
- .travis.yml
- codecov.yml
- setup.cfg
- src/qmflows/components/reactivity.py
- src/qmflows/cp2k_utils.py
- src/qmflows/data/__init__.py
- src/qmflows/data/dictionaries/__init__.py
- src/qmflows/examples/Conditional_workflows/__init__.py
- src/qmflows/examples/Conditional_workflows/calc_freqs.py
- src/qmflows/examples/Constrained_and_TS_optimizations/H2O2_TS.py
- src/qmflows/examples/Constrained_and_TS_optimizations/__init__.py
- src/qmflows/examples/Constrained_and_TS_optimizations/generic_constraints.py
- src/qmflows/examples/Constrained_and_TS_optimizations/partial_geometry_opt.py
- src/qmflows/examples/__init__.py
- src/qmflows/packages/SCM.py
- src/qmflows/packages/__init__.py
- src/qmflows/packages/cp2k_mm.py
- src/qmflows/packages/cp2k_package.py
- src/qmflows/packages/orca.py
- src/qmflows/packages/serializer.py
- src/qmflows/parsers/cp2KParser.py
- src/qmflows/settings.py
- src/qmflows/templates/__init__.py
Implementation of https://github.com/SCM-NV/qmflows/issues/202:
> Run pydocstyle and pycodestyle over src/

- conftest.py
- docs/conf.py
- setup.cfg
- src/qmflows/backports.py
- src/qmflows/cp2k_utils.py
- src/qmflows/packages/package_wrapper.py
- src/qmflows/packages/packages.py
- src/qmflows/settings.py
- src/qmflows/test_utils.py
- src/qmflows/utils.py
Implementation of https://github.com/SCM-NV/qmflows/issues/177.
> Added doctests

- src/qmflows/parsers/cp2KParser.py
- src/qmflows/templates/templates.py
* Reduce the CP2K output level to `LOW` 
* If the CP2K computation is unrestricted, search for 2 spin states in the output file
> use the CP2K spin states information to parse the output

- src/qmflows/parsers/cp2KParser.py
use [subprocess.check_call](https://docs.python.org/3.8/library/subprocess.html#subprocess.check_call) instead of [subprocess.check_output](https://docs.python.org/3.8/library/subprocess.html#subprocess.check_output)
> Cp2k unrestricted

- src/qmflows/parsers/cp2KParser.py
CP2K prints either `HOMO-LUMO` or `Fermi` at the end of the orbitals file. We were only using the `HOMO-LUMO` to identify the end of the orbitals. We should use both keyword to signal the end of a set of orbitals.
> used either HOMO-LUMO or Fermi keywords to split cp2k orbitals

- src/qmflows/packages/package_wrapper.py
- test/test_cp2k_mock.py
The `dill_path` and `plams_dir` parameters were swapped around.
> Fixed an issue where an `ResultWrapper` parameters were incorrectly ordered

- test/test_adf_mock.py
- test/test_cp2k_mm_mock.py
- test/test_cp2k_mock.py
- test/test_dftb_mock.py
- test/test_mock_operations.py
- test/test_orca_mock.py
the mocked test are redefining the mocker object like:
```pyhon
from pytest_mock import mocker
def test_foo(mocker):
...
```
The `import` statement is not necessary because pytest is already adding the `mocker` object.
> removed mocker from import

- src/qmflows/packages/SCM.py
- src/qmflows/packages/cp2k_mm.py
- src/qmflows/packages/cp2k_package.py
- src/qmflows/packages/orca.py
- src/qmflows/packages/package_wrapper.py
- src/qmflows/packages/packages.py
- src/qmflows/packages/serializer.py
- test/test_sphinx.py
This PR adds three new attributes to `Package`, thus making its instances fully compatible with `typing.Callable` (or more specifically the typing-only `builtins.function` class).
Note that this does not affect the `Package` *class*, only its instances are affected which are callables in their own right.
> Make `Package` instances compatible with `builtins.function`

- src/qmflows/packages/SCM.py
- src/qmflows/packages/cp2k_mm.py
- src/qmflows/packages/cp2k_package.py
- src/qmflows/packages/orca.py
- src/qmflows/packages/package_wrapper.py
- src/qmflows/packages/packages.py
- test/test_sphinx.py
This PR adds the `validate_output` keyword to `Package.__call__` and `run_job`, the determining whether or not the output should be checked for warnings.
The motivation behind this PR is the fact that output validation _can_ be very slow for large `.out` files,
situations wherein it is thus desirable to skip this step in its entirety.
> Add the `validate_output` keyword to `Package`

- src/qmflows/packages/cp2k_mm.py
The CP2K [`USE_ELEMENT_AS_KIND`](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/SUBSYS/TOPOLOGY.html#list_USE_ELEMENT_AS_KIND) ensures that an atom kind is automatically generated for each atomic symbol in the molecule. Because of this the keyword is automatically set to `.TRUE.` if no .psf file has been provided.
The problem is that this is a relatively new keyword (CP2K >= 7 I believe?). 
This PR thus removes the `USE_ELEMENT_AS_KIND` key and instead explicitly specifies a `kind` block for each individual atomic symbol.
> Do not use the CP2K `USE_ELEMENT_AS_KIND` keyword

- src/qmflows/templates/templates.py
- src/qmflows/test_utils.py
The issue with supplying with the CP2K [`cell.abc`](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/SUBSYS/CELL.html#ABC) key is that it complicates the use of a number of other keys 
(_i.e._ `a`, `b` and `c`). Better remove it and let the user explicitly specify a value.
> MAINT: Remove the cell parameters from the `cp2k_mm` templates

- src/qmflows/packages/packages.py
Apparently the wrapper of `qmflows.Result` around `plams.Results` was failing to work when initially opening.
The problem was due to a recursive call `Result__getattr__`, a problem that has been resolved by directly performing a `__getitem__` operation on the classes' underlying  instance-attribute-containing dictionary.
Examples
----------
The previous behavior:
``` python
>>> from qmflows.packages import Result
>>> result: Result = ...
>>> result.get_hirshfeld_charges()  # Fails
None
>>> result.get_hirshfeld_charges()  # Works fine as the `plams.Result`-containing .dill file has been unpickled
[...]
```
> BUG: Fixed an issue where `Result.__getattr__` could fail

- src/qmflows/packages/cp2k_mm.py
Quite a minor fix, `CP2KMM_Result` now correctly inherits from the latter.
> Fixed an issue where `CP2KMM_Result` did not inherit from `CP2K_Result`

- src/qmflows/data/dictionaries/propertiesCP2K.yaml
- src/qmflows/data/dictionaries/propertiesCP2KMM.yaml
- src/qmflows/packages/packages.py
- src/qmflows/parsers/cp2KParser.py
This PR adds the new `CP2K_Result.lattice` property, 
the latter returning all lattice vectors over the course of a trajectory; `shape = (n_mol, 3, 3)`.
> ENH: Added the new `lattice` property to `CP2K_Result`

- src/qmflows/templates/templates.py
Forgot to change the default `o_spline` values in the other `cp2k_mm` templates besides `cell_opt` (xref https://github.com/SCM-NV/qmflows/pull/239).
> MAINT:  Use `o_spline = 4` for all other `cp2k_mm` the templates

- src/qmflows/packages/cp2k_package.py
- test/test_special_keywords.py
closes https://github.com/SCM-NV/qmflows/issues/243.
Resolves aforementioned issue by removing the 2-digits restriction from the CP2K cell parameters.
> MAINT: Remove the 2-digit restriction from CP2K cell parameters

- src/qmflows/fileFunctions.py
- src/qmflows/templates/templates.py
- src/qmflows/yaml_utils.py
- test/test_yaml_settings.py
Xref https://github.com/SCM-NV/nano-qmflows/issues/308.
This PR adds a set of three `yaml` loaders that raise upon encountering duplicate keys.
The loaders come in three flavors, each being based on either `yaml.UnsafeLoader` (aka `yaml.Loader`), `yaml.FullLoader` or `yaml.SafeLoader`.
> ENH: Add new `yaml` loaders with duplicate key checking

- .github/workflows/pythonapp.yml
- setup.py
- src/qmflows/__init__.py
- test/test_templates.py
This PR adds a module-level `__getattr__` (see [PEP 562](https://www.python.org/dev/peps/pep-0562/)) in order to ensure that qmflows templates are 
always copied when getting them. This should prevent issues wherein the (extremelly mutable) settings 
instance is altered inplace, which can result in some rather nasty and difficult to diagnose bugs.
> ENH: Ensure that the qmflows templates are always copied

- .github/workflows/pythonapp.yml
- setup.py
- src/qmflows/__init__.py
- test/test_templates.py
cc @rlKoekie.
I wasn't aware that SCM was still shipping Python 3.6.
Out of curiosity, are there any plans for updating the SCM-distributed python version?
Considering 3.6 is almost 5 years old at this point.
> REV: Reintroduce support for python 3.6

- src/qmflows/cp2k_utils.py
Added in CP2K version 8; see the [CP2K manual](https://manual.cp2k.org/cp2k-8_2-branch/CP2K_INPUT/FORCE_EVAL/MM/FORCEFIELD/NONBONDED/GAL19.html).
> ENH: Add a generic keyword for the CP2K `GAL19` non-bonded forcefield

- .github/workflows/pythonapp.yml
- docs/conf.py
- setup.py
Closes https://github.com/SCM-NV/qmflows/issues/250.
The `sudo apt install cp2k` command was broken some time ago, see if it is working again.
> TST: Re-enable the CP2K tests

- src/qmflows/__init__.py
- src/qmflows/parsers/cp2KParser.py
- test/test_cp2k_parser.py
Allow the CP2K executable to contain spaces whenever extracting it from the .run file.
> MAINT: Allow the CP2K executable to contain spaces

- CHANGELOG.md
- src/qmflows/templates/templates.py
- test/test_using_plams/test_cp2k.py
This PR adds the `qmflows.freq.cp2k` template, which can be used for performing frequency analyses.
The template is effectively a hybrid of the pre-existing `freq.cp2k_mm` and `singlepoint.cp2k` templates.
> ENH: Add a frequency analysis template for CP2K

- setup.py
- src/qmflows/packages/packages.py
- test/test_cp2k_mock.py
Adds the `Result.__dir__` method so that qmflows' generic properties are automatically picked up by autocompletion tools.
> ENH: Add `Result.__dir__`

- src/qmflows/packages/SCM.py
- src/qmflows/packages/packages.py
- src/qmflows/test_utils.py
- test/test_cp2k_mm_mock.py
- test/test_cp2k_mock.py
- test/test_using_plams/test_cp2k.py
- test/test_using_plams/test_cp2k_mm.py
- test/test_utils.py
Print the last 100 lines of the .err and .out file whenever a test job crashes.
> TST: Print the CP2K .out and .err files whenever a test job crashes

- src/qmflows/common.py
- src/qmflows/parsers/_cp2k_basis_parser.py
- test/test_cp2k_parser.py
Removed again, as it makes membership checks a lot more difficult in https://github.com/SCM-NV/nano-qmflows/pull/353.
> REV: Remove the `AtomBasisKey.alias` field again

- .github/workflows/pythonapp.yml
- setup.py
Allows for automatic installation of the new noodles 0.3.4 release.
> BLD: Remove the upper version bound of noodles

- .github/workflows/pythonapp.yml
- src/qmflows/test_utils.py
Distutils is deprecated per [PEP 632](https://www.python.org/dev/peps/pep-0632/) and stated for removal in python 3.12.
> DEP: Vendor a copy of `distutils.spawn.find_executable`

- setup.py
pyparsing >3.0 initially causes some test failures back in https://github.com/SCM-NV/qmflows/pull/255, check if those have now been resolved.
> BLD: Try removing the upper version bound of `pyparsing`

- src/qmflows/parsers/cp2KParser.py
- test/test_cp2k_mock.py
- test/test_cp2k_parser.py
Using `cp2k.popt --version` can fail if the CP2K version used for constructing a given output is 
different from the version that's currently loaded.
Instead, read the version directly from the .out file.
> MAINT: Do not extract the CP2K version via `cp2k.popt --version`

- src/qmflows/parsers/cp2k.py
There seems to be a CP2K bug (?) as of 8.2 where the number of occupied orbitals isn't always printed.
Explicitly raise an exception when this occurs.
Examples
----------
```
Number of electrons:                                                          2
Number of occupied orbitals:                                                    <--- where are they!???
TOTAL NUMBERS AND MAXIMUM NUMBERS
```
> MAINT: Explicitly raise when the line with the number of orbitals doesn't have any actual orbitals

- CHANGELOG.md
- CITATION.cff
- MANIFEST.in
- setup.cfg
- src/qmflows/_version.py
- src/qmflows/common.py
- src/qmflows/packages/_cp2k.py
- src/qmflows/parsers/_cp2k_orbital_parser.py
- test/test_common.py
Add the MO index and occupation numbers to the CP2K orbital output.
> ENH: Add two new fields to CP2K MO named tuple 

- .github/workflows/pythonapp.yml
- .readthedocs.yml
- conftest.py
- doc_environment.yml
- pyproject.toml
- src/qmflows/packages/_scm.py
- src/qmflows/parsers/_cp2k_basis_parser.py
- src/qmflows/parsers/_cp2k_orbital_parser.py
- src/qmflows/parsers/cp2k.py
- src/qmflows/parsers/utils.py
- src/qmflows/test_utils.py
- src/qmflows/utils.py
- test/test_special_keywords.py
- test/test_utils.py
- test/test_xyz_parser.py
> TST: Enable tests for python 3.12
