SCM-NV/qmflows

qmworks/examplesWorkflows/Linear_TS/linear_TS.py
qmworks/examplesWorkflows/OptimizeH2O/OptimizeH2O.py
qmworks/packages/packages.py
test/test_ADFGeometry_Constraints.py
test/test_molecule.py

Uses some more recent features of Noodles, als needs the patched version of plams.

Job caching and meaningful messages on screen

---

requirements.txt

Update installation instructions

update installation instructions

---

qmworks/packages/packages.py

Added a serialization for the Path class in the registry function (packages.py)

add Path serializer from Noodles

---

qmworks/packages/SCM.py
qmworks/packages/cp2k_package.py
qmworks/packages/orca.py

Fixed [issue-16](https://github.com/SCM-NV/qmworks/issues/16).

added job_name to the result Object

---

qmworks/hdf5/quantumHDF5.py
qmworks/molkit.py
qmworks/packages/packages.py
test/test_parser_turbomole.py
test/test_using_plams/test_transfer_hessian.py

improved style

---

setup.py
src/qmflows/__init__.py
src/qmflows/components/__init__.py
src/qmflows/components/qd_ams.py
src/qmflows/components/qd_functions.py
src/qmflows/components/qd_import_export.py
src/qmflows/components/qd_ligand_opt.py
src/qmflows/components/qd_ligand_rotate.py
src/qmflows/qd.py

- Ligand optimization functions moved from qd_functions.py to qd_ligand_opt.py.
- Functions related to creating quantum dots (core + ligand -> quantum dot) moved from qd.py and qd_functions.py to qd_ligand_rotate.py.
- New vectorized approach for attaching ligands to the core (see qd_ligand_rotate.py).
- A number of optimizations in qd_ligand_opt.py.
- A few redundant functions removed.
- Added Scipy to install_requires in setup.py.

qd_functions trimmed down; new approach to attaching ligands to the core

---

src/qmflows/components/qd_ligand_opt.py

Molecule and Atom are now, again, imported from the correct module

Fixed importing of Molecule and Atom

---

src/qmflows/templates/templates.py

Fixed a missing indentation level in the ADF singlepoint template

Fixed a missing indentation level

---

test/test_restart_init.py

Added a missing ``finish()`` call to the ``init_restart()`` test.

Added missing ``finish()`` call

---

setup.py

Added ``"pandas"`` to ``install_requires`` in ``setup.py``.

pandas somehow disappeared from install_requires

---

src/qmflows/common.py
src/qmflows/cp2k_utils.py
src/qmflows/packages/SCM.py
src/qmflows/packages/cp2k_mm.py
src/qmflows/packages/cp2k_package.py
src/qmflows/packages/gamess.py
src/qmflows/packages/orca.py
src/qmflows/packages/package_wrapper.py
src/qmflows/packages/packages.py
src/qmflows/parsers/cp2KParser.py
src/qmflows/templates/templates.py
src/qmflows/type_hints.py
src/qmflows/warnings_qmflows.py
test/test_using_plams/test_cp2k_mm.py

See https://github.com/SCM-NV/qmflows/issues/159.
Major
-----
* Updated the ``Warning`` management in QMFlows. All issued warnings are now instances of ``QMFlows_Warning`` or one of its subclasses.
* Updated the general structure of ``cp2k_warnings``.
* Added warnings for ``CP2KMM``.
Minor
------
* Added a dedicated module for type hints.
* Changed a number of absolute import paths to relative ones.
* Added Sphinx-readable comments to the QMFlows templates.

Package and CP2KMM upgrades

---

src/qmflows/packages/cp2k_package.py
test/test_cp2k_mock.py

fixed CP2K_RESULT construction

---

setup.py
src/qmflows/backports.py
src/qmflows/common.py
src/qmflows/components/operations.py
src/qmflows/cp2k_utils.py
src/qmflows/parsers/adf_parser.py
src/qmflows/parsers/cp2KParser.py
src/qmflows/parsers/generic_parsers.py
src/qmflows/parsers/orca_parser.py
src/qmflows/parsers/parser.py
src/qmflows/parsers/xyzParser.py
src/qmflows/test_utils.py
src/qmflows/utils.py
src/qmflows/warnings_qmflows.py
test/test_files/mypy.ini
test/test_mypy.py
test/test_warnings.py

See https://github.com/SCM-NV/qmflows/issues/176.
[Mypy](https://github.com/python/mypy) is an optional static type checker for Python that aims to combine the benefits of dynamic (or "duck") typing and static typing. [Mypy](https://github.com/python/mypy) combines the expressive power and convenience of Python with a powerful type system and compile-time type checking. [Mypy](https://github.com/python/mypy) type checks standard Python programs; run them using any Python VM with basically no runtime overhead. 
Major
------
* Introduced tests using MyPy.
* Refined existing type hints.
Minor
------
* Fixed the occasional ``AttributeError`` that might be raised due to unexpected ``None`` values.
Open question
---------------
* ~~Should these newly introduced test raise an ``Exception`` or …

Added static code tests using MyPy

---

src/qmflows/__init__.py
src/qmflows/examples/Constrained_and_TS_optimizations/H2O2_TS.py
src/qmflows/examples/Constrained_and_TS_optimizations/generic_constraints.py
src/qmflows/examples/Constrained_and_TS_optimizations/partial_geometry_opt.py
src/qmflows/logger.py
src/qmflows/packages/packages.py
test/test_orca_parser.py
test/test_overlay.py
test/test_reactivity.py
test/test_using_plams/test_failure_package.py
test/test_using_plams/test_freq_ethene_DFTB.py
test/test_using_plams/test_opt_orca.py
test/test_using_plams/test_transfer_hessian.py

* Added a dedicated ``Logger`` to the ``qmflows.logger`` module.
* Replaced all ``print()`` calls with ``Logger.info()``.
* Replaced a number of leftover ``assert`` statements with calls to ``assertionlib.assertion``.

Added a QMFlows Logger

---

requirements.txt
setup.py
src/qmflows/backports.py
test/test_backports.py

* Cleaned up the ``qmflows.backports`` module.
* Fix the PLAMS version to https://github.com/SCM-NV/PLAMS/commit/a5696ce62c09153a9fa67b2b03a750913e1d0924.

Cleaned up the backports module

---

CHANGELOG.md
src/qmflows/parsers/cp2KParser.py

improve cp2k error report

---

CHANGELOG.md
src/qmflows/__version__.py
src/qmflows/common.py
src/qmflows/parsers/cp2KParser.py
src/qmflows/templates/templates.py
test/test_cp2k_mock.py
test/test_orca_mock.py

solve CP2K parsing issue

---

src/qmflows/parsers/cp2KParser.py

Try to fix [nano-qmflows#283](https://github.com/SCM-NV/nano-qmflows/issues/283)

check that the orbitals for unrestricted calculations is created

---

src/qmflows/parsers/cp2KParser.py

Check for the "HOMO-LUMO" or "Fermi" keywords in the unrestricted log files

Cp2k unrestricted

---

src/qmflows/data/dictionaries/propertiesCP2K.yaml
src/qmflows/data/dictionaries/propertiesCP2KMM.yaml
src/qmflows/parsers/cp2KParser.py

The properties in question (all are returned as arrays):
* `volume`: the cell-volume across the trajectory; `shape = (n_mol,)`
* `forces`: the atomic forces across the trajectory; `shape = (n_mol, n_atom, 3)`
* `coordinates`: the atomic coordinates across the trajectory; `shape = (n_mol, n_atom, 3)`
* `temperature`: the temperature across the trajectory; `shape = (n_mol,)`

ENH: Add 4 new properties to `CP2K_Result`

---

src/qmflows/packages/cp2k_package.py

Minor improvement to the generic `cell_parameters` keyword:
It can now take any array-like object, not just (nested) lists.

ENH: Allow the generic `cell_parameters` keyword to take any array-like object

---

.readthedocs.yml
environment.yml

Readthedocs keep crashing creating the latex-based docs.

DOC: Disable the RTD epub format

---

.readthedocs.yml

https://github.com/SCM-NV/qmflows/pull/252 did not fix the issue.

DOC: Build the readthedocs `epub` format instead of `format`

---

.github/workflows/pypi.yml
setup.cfg
setup.py

Automatically publish to PyPi whenever creating a new release on GitHub.

BLD: Add a GitHub Actions workflow for automatic PyPi publishing

---

setup.cfg
src/qmflows/examples/Conditional_workflows/calc_freqs.py
src/qmflows/examples/Constrained_and_TS_optimizations/H2O2_TS.py
src/qmflows/examples/Constrained_and_TS_optimizations/generic_constraints.py
src/qmflows/examples/Constrained_and_TS_optimizations/partial_geometry_opt.py
src/qmflows/test_utils.py
src/qmflows/utils.py
test/test_adf_mock.py
test/test_runner.py
test/test_sphinx.py
test/test_using_plams/test_ADFGeometry_Constraints.py
test/test_using_plams/test_conditional_workflows.py
test/test_using_plams/test_cp2k_mm.py
test/test_using_plams/test_cp2k_opt.py
test/test_using_plams/test_failure_package.py
test/test_using_plams/test_freq_ethene_DFTB.py
test/test_using_plams/test_get_properties.py
test/test_using_plams/test_opt_orca.py
test/test_using_plams/test_package_wrapper.py
test/test_using_plams/test_transfer_hessian.py
test/test_utils.py

closes https://github.com/SCM-NV/qmflows/issues/269

 BUG: Fixed an issue wherein `init_restart`/`InitRestart` could fail on consecutive calls

---

src/qmflows/parsers/cp2KParser.py

closes https://github.com/SCM-NV/nano-qmflows/issues/338
cc @IndyduFosse

MAINT: Recognize `Band gap` as a valid footer in the CP2K >=8.2 MOLog

---

.github/workflows/pythonapp.yml

Add tests for the CP2K 9.1 release: https://www.cp2k.org/version_history

TST: Add CP2K 9.1 tests
